[1/6] cd /home/varun/esp/OTA_ESP/build/esp-idf/esptool_py && /home/varun/.espressif/python_env/idf5.4_py3.10_env/bin/python /home/varun/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 partition --type app /home/varun/esp/OTA_ESP/build/partition_table/partition-table.bin /home/varun/esp/OTA_ESP/build/OTA_ESP.bin
OTA_ESP.bin binary size 0xcdfe0 bytes. Smallest app partition is 0x170000 bytes. 0xa2020 bytes (44%) free.
[2/6] Performing build step for 'bootloader'
[1/1] cd /home/varun/esp/OTA_ESP/build/bootloader/esp-idf/esptool_py && /home/varun/.espressif/python_env/idf5.4_py3.10_env/bin/python /home/varun/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/varun/esp/OTA_ESP/build/bootloader/bootloader.bin
Bootloader binary size 0x6570 bytes. 0xa90 bytes (9%) free.
[3/4] cd /home/varun/esp/OTA_ESP/build && /home/varun/.espressif/python_env/idf5.4_py3.10_env/bin/python /home/varun/esp/esp-idf/components/spiffs/spiffsgen.py 0x100000 /home/varun/esp/OTA_ESP/spiffs /home/varun/esp/OTA_ESP/build/storage.bin --page-size=256 --obj-name-len=32 --meta-len=4 --use-magic --use-magic-len
[3/4] cd /home/varun/esp/esp-idf/components/esptool_py && /usr/bin/cmake -D IDF_PATH=/home/varun/esp/esp-idf -D "SERIAL_TOOL=/home/varun/.espressif/python_env/idf5.4_py3.10_env/bin/python;;/home/varun/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/home/varun/esp/OTA_ESP/build -P /home/varun/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
esptool.py --chip esp32 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 bootloader/bootloader.bin 0x20000 OTA_ESP.bin 0x8000 partition_table/partition-table.bin 0xf000 ota_data_initial.bin 0x300000 storage.bin
esptool.py v4.9.0
Serial port /dev/ttyUSB0

A fatal error occurred: Could not open /dev/ttyUSB0, the port is busy or doesn't exist.
([Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0')

Hint: Check if the port is correct and ESP connected

FAILED: CMakeFiles/flash /home/varun/esp/OTA_ESP/build/CMakeFiles/flash 
cd /home/varun/esp/esp-idf/components/esptool_py && /usr/bin/cmake -D IDF_PATH=/home/varun/esp/esp-idf -D "SERIAL_TOOL=/home/varun/.espressif/python_env/idf5.4_py3.10_env/bin/python;;/home/varun/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/home/varun/esp/OTA_ESP/build -P /home/varun/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
ninja: build stopped: subcommand failed.
